name: C/C++ CI
permissions:
    contents: read
    pull-requests: write

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install g++

    - name: Build C++
      run: g++ -o main main.cpp

    - name: Run executable
      run: |
        GITHUB_USER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
        ./main "$GITHUB_USER"
